Update 11_selection.md
Fix bug. Code on page 127 in pdf failed with this trace:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[19], line 1
----> 1 secondsmallest(L)

Cell In[18], line 5, in secondsmallest(L)
      3 a, b = None, None
      4 for item in L:
----> 5     if a is None or item <= b:
      6         a, b = item, a
      7     elif b is None or item <= a:

TypeError: '<=' not supported between instances of 'int' and 'NoneType'